---
- name: Swap App server Active group
  hosts: app-https-lb
  vars:
  tasks:
    - name: update HAProxy config     
      copy:
        src: /etc/ansible/application-files/haproxy-group-b.cfg
        dest: /etc/haproxy/haproxy.cfg
      when: ansible_os_family == "RedHat"
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
      when: ansible_os_family == "RedHat"
