---
- name: Release Update for application App Servers
  hosts: prod-appsrv-tls
  vars:
     newver: 3939
  tasks:
    - name: Import variables and tasks
      include_vars: 
        dir: /etc/ansible/include_vars/
    - name: Checking App server version
      include_tasks: /etc/ansible/tasks/appsrv_mtver.yml
    - name: Create Date Folder
      win_file: path=c:\Installs\{{ newver }} state=directory
    - name: Copy application 5.5 Installation
      win_copy: src=/etc/ansible/application-files/{{ newver }}/application.{{ newver }}.msi dest=c:\\Installs\\{{ newver }}\\application.{{ newver }}.msi
    - name: Copy application App Server Installation
      win_copy: src=/etc/ansible/application-files/{{ newver }}/AppServerServices.{{ newver }}.msi dest=c:\\Installs\\{{ newver }}\\AppServerServices.{{ newver }}.msi
    - name: Stop Data Host Service
      win_service: 
        name: "application Data Host"
        state: stopped
    - name: Stop Event Monitor Service
      win_service: 
        name: "application Event Monitor"
        state: stopped
    - name: Backup App Server Settings.xml
      win_copy: 
         src: C:\Program Files (x86)\application 5.0 Application Server Services\Settings.xml
         dest: C:\Program Files (x86)\Settings.xml
         remote_src: True
    - name: Uninstall App server
      win_package: 
          path: c:\\Installs\\{{ oldappsrvver }}\\AppServerServices.{{ oldappsrvver }}.msi
          extra_args: /qn
          present: absent
    - name: Delete AppServer files
      win_file: 
          path: C:\\Program Files (x86)\\Application Server
          state: absent
    - name: Uninstall 5.5 desktop
      win_package: 
          path: c:\\Installs\\{{ old55ver }}\\application.{{ old55ver }}.msi
          extra_args: /qn
          present: absent
    - name: Install application 5.5 App
      win_package: 
          path: c:\\Installs\\{{ newver }}\\application.{{ newver }}.msi
          extra_args: /qn
    - name: Install application App Server
      win_package: 
          path: c:\\Installs\\{{ newver }}\\AppServerServices.{{ newver }}.msi
          extra_args: /qn
    - name: Copy App Server Settings.xml
      win_copy: 
         src: C:\Program Files (x86)\Settings.xml
         dest: C:\Program Files (x86)\application 5.0 Application Server Services\Settings.xml
         remote_src: True
      when: inventory_hostname != "export.services.local"
    - name: Set data host Service Recovery options
      script: /etc/ansible/application-files/scripts/set-srvrecovery.bat
    - name: Set Data Host Service to auto
      win_service: 
        name: "application Data Host"
        state: restarted
        start_mode: auto
    - name: Set Event Monitor Service to auto
      win_service: 
        name: "application Event Monitor"
        state: restarted
        start_mode: auto
